### ISSUE TITLE
segfault with nxagent 3.5.99.2

### ISSUE THREAD

**Issue by sunweaver** [ArcticaProject/nx-libs#224]
$  export LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu"/nx-X11/
$ gdb /usr/lib/x86_64-linux-gnu/nx/bin/nxagent

```

[...]

(gdb) run :1
Starting program: /usr/lib/x86_64-linux-gnu/nx/bin/nxagent :1
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

NXAGENT - Version 3.5.99.2

Copyright (c) 2001, 2011 NoMachine (http://www.nomachine.com)
Copyright (c) 2008-2014 Oleksandr Shneyder <o.shneyder@phoca-gmbh.de>
Copyright (c) 2011-2016 Mike Gabriel <mike.gabriel@das-netzwerkteam.de>
Copyright (c) 2014-2016 Ulrich Sibiller <uli42@gmx.de>
Copyright (c) 2014-2016 Mihai Moldovan <ionic@ionic.de>
Copyright (c) 2015-2016 Qindel Group (http://www.qindel.com)
See https://github.com/ArcticaProject/nx-libs for more information.

Info: Agent running with pid '32761'.
Session: Starting session at 'Thu Oct 13 15:45:12 2016'.

Program received signal SIGSEGV, Segmentation fault.
_X11TransConnect (ciptr=0x55bf3b30, address=0x7fffffffda50 "local/:0") at ../../exports/include/nx-X11/Xtrans/Xtrans.c:864
864     ret = ciptr->transptr->Connect (ciptr, host, port);
(gdb) bt full 
#0  _X11TransConnect (ciptr=0x55bf3b30, address=0x7fffffffda50 "local/:0") at ../../exports/include/nx-X11/Xtrans/Xtrans.c:864
        protocol = 0x555555bf3ad0 "local"
        host = 0x555555bf3ab0 "minobo"
        port = 0x555555bf3b90 "0"
        ret = <optimized out>
#1  0x00007ffff5c35f91 in _X11TransConnectDisplay (display_name=0x7fffffffda50 "local/:0", fullnamep=0xffffffff, dpynump=0x555555bf3b90, screenp=0x0, auth_namep=0x0, auth_namelenp=0x555555bf3af0, 
    auth_datap=0x7fffffffde20, auth_datalenp=0x7fffffffde08) at ConnDis.c:583
        family = 0
        saddrlen = 0
        saddr = 0x0
        pprotocol = 0x555555bf3a90 "local"
        len = -9648
        addrbuf = "local/:0\000\300\237\365\377\177\000\000P\340\377\377\377\177\000\000p\033\213UUU\000\000\207(\255\373\000\000\000\000~\303i\365\377\177\000\000\000\000\000\000\000\000\000\000\260\340\377\377\377\177\000\000\250\340\377\377\377\177\000\000\247\340\377\377\377\177\000\000\204\332\377\377\377\177\000\000 \000\000\000\060\000\000\000 \341\377\377\377\177\000\000`\340\377\377\377\177\000\000\260\333\377\377\377\177\000\000@j\377\367\377\177\000"
        address = 0x7fffffffda50 "local/:0"
        connect_stat = 1438595984
        local_transport_index = 0
        local_transport = {0x7ffff5cc2598 "local", 0x7ffff5cc259e "unix", 0x7ffff5cc25a3 "tcp", 0x0}
#2  0x00007ffff5c48d36 in XOpenDisplay (display=0x555555bd7a00 <nxagentDisplayName> ":0") at OpenDis.c:221
        dpy = 0x555555bf2820
        i = 1438480896
        client = {byteOrder = 0 '\000', pad = 0 '\000', majorVersion = 0, minorVersion = 0, nbytesAuthProto = 0, nbytesAuthString = 0, pad2 = 0}
        idisplay = -177688352
---Type <return> to continue, or q <return> to quit---
        prefixread = 1438480896
        conn_auth_name = 0x4000000 <error: Cannot access memory at address 0x4000000>
        conn_auth_data = 0x7ffff568b0e0 <__restore_rt> "H\307\300\017"
        conn_auth_namelen = 32767
        conn_auth_datalen = 8192
        setup = 0x555555bd6e18 <clients> "\220\377\276UUU"
        fullname = 0x0
        iscreen = 0
        prefix = {success = 0 '\000', lengthReason = 0 '\000', majorVersion = 0, minorVersion = 0, length = 0}
        setuplength = 0
        usedbytes = 93824999062016
        conn_buf_size = 1
        xlib_buffer_size = 0x1 <error: Cannot access memory at address 0x1>
#3  0x00005555555f8e85 in nxagentInternalOpenDisplay (display=display@entry=0x555555bd7a00 <nxagentDisplayName> ":0") at Display.c:645
        newDisplay = <optimized out>
        oldAction = {__sigaction_handler = {sa_handler = 0x5555555e7980 <SmartScheduleTimer>, sa_sigaction = 0x5555555e7980 <SmartScheduleTimer>}, sa_mask = {__val = {8192, 140737310666976, 
              18446744067267100671, 18446744073709551615 <repeats 13 times>}}, sa_flags = 67108864, sa_restorer = 0x7ffff568b0e0 <__restore_rt>}
        newAction = {__sigaction_handler = {sa_handler = 0x5555555f8030 <nxagentRejectConnection>, sa_sigaction = 0x5555555f8030 <nxagentRejectConnection>}, sa_mask = {__val = {18446744067267100671, 
              18446744073709551615 <repeats 15 times>}}, sa_flags = 0, sa_restorer = 0xffffffffffffffff}
        result = <optimized out>
#4  0x00005555555f9998 in nxagentOpenDisplay (argc=argc@entry=2, argv=argv@entry=0x7fffffffe2f8) at Display.c:1217
        i = <optimized out>
#5  0x0000555555608816 in InitOutput (screenInfo=0x555555bd6d40 <screenInfo>, argc=2, argv=0x7fffffffe2f8) at Init.c:334
        authority = 0x0
---Type <return> to continue, or q <return> to quit---
        i = <optimized out>
#6  0x0000555555597731 in main (argc=2, argv=0x7fffffffe2f8, envp=<optimized out>) at main.c:358
        i = <optimized out>
        j = 2
        k = 2
        error = 0
        xauthfile = <optimized out>
        alwaysCheckForInput = {0, 1}
```

**Comment by uli42** [comment]
At first glance it looks like your $DISPLAY is set to `local:/0` which I have never seen anywhere. Can you please set it to :0 and retry?

**Comment by uli42** [comment]
Just to be sure: can you please run `ldd /usr/lib/x86_64-linux-gnu/nx/bin/nxagent` and check, if the system's libX11 is appearing in the list (it should NOT!)?

**Comment by uli42** [comment]
I cannot seem to provoke this with a fresh compile on Ubuntu 14.04. What OS are you running?

Also, I have just rebased the pr/further_backports branch. Can you please retry with that?

**Comment by sunweaver** [comment]
I see this on Debian jessie and Debian unstable.

Also the build logs contain this: 

```
gcc -c -D_FORTIFY_SOURCE=2 -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -g -std=c99 -Wall -Wpedantic -Wpointer-arith -Wundef    -I../.. -I../../exports/include   -Dlinux -D__amd64__ -D_POSIX_C_SOURCE=199309L                               -D_POSIX_SOURCE -D_XOPEN_SOURCE                                 -D_DEFAULT_SOURCE                                 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64                             -D_GNU_SOURCE                            -DFUNCPROTO=15 -DNARROWPROTO -DXTHREADS  -D_REENTRANT -DXUSE_MTSAFE_API    -DMALLOC_0_RETURNS_NULL  -DHAS_SNPRINTF -DLIBX11                   -DPOSTLOCALELIBDIR=\"lib\" -I../../../nxcomp -DNX_TRANS_SOCKET              -DNX_TRANS_EXIT -DXCMS -DUSE_XCB=0   -I../../include/extensions   -DFAIL_HARD -DXKB   -fPIC OpenDis.c
OpenDis.c: In function ‘XOpenDisplay’:
OpenDis.c:230:2: warning: implicit declaration of function ‘_X11TransGetConnectionNumber’ [-Wimplicit-function-declaration]
  dpy->fd = _X11TransGetConnectionNumber (dpy->trans_conn);
  ^
```

**Comment by uli42** [comment]
I see those, too, and my system works.

I am suspecting you are using abstract sockets. But it looks like we
never compile the needed code, I cannot find where
HAVE_ABSTRACT_SOCKETS is defined.

**Comment by sunweaver** [comment]
In lib/xtrans/Xtrans.c, you can find TRANS(ParseAddress). The comment at the top of the function explains the "local/:0" syntax of display_name.

Also, TRANS(ParseAddress) adds the local/ part if no hostname is given.

And of course, we want to support ABSTRACT_SOCKETS.

**Comment by sunweaver** [comment]
in X.org's Xtrans/Xtranssock.c, I find:

```
#ifdef linux
#define HAVE_ABSTRACT_SOCKETS
#endif
```

**Comment by sunweaver** [comment]
And we have that, too. But why do you mention it here?

**Comment by sunweaver** [comment]
```
(gdb) run :1
Starting program: /usr/lib/x86_64-linux-gnu/nx/bin/nxagent :1
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

NXAGENT - Version 3.5.99.2

Copyright (c) 2001, 2011 NoMachine (http://www.nomachine.com)
Copyright (c) 2008-2014 Oleksandr Shneyder <o.shneyder@phoca-gmbh.de>
Copyright (c) 2011-2016 Mike Gabriel <mike.gabriel@das-netzwerkteam.de>
Copyright (c) 2014-2016 Ulrich Sibiller <uli42@gmx.de>
Copyright (c) 2014-2016 Mihai Moldovan <ionic@ionic.de>
Copyright (c) 2015-2016 Qindel Group (http://www.qindel.com)
See https://github.com/ArcticaProject/nx-libs for more information.

Info: Agent running with pid '7891'.
Session: Starting session at 'Thu Oct 13 20:21:47 2016'.

Breakpoint 1, _X11TransConnect (ciptr=ciptr@entry=0x55bf7da0, address=address@entry=0x7fffffffdc20 "local/:0") at ../../exports/include/nx-X11/Xtrans/Xtrans.c:840
840 ../../exports/include/nx-X11/Xtrans/Xtrans.c: No such file or directory.
(gdb) s
848 in ../../exports/include/nx-X11/Xtrans/Xtrans.c
(gdb) n
840 in ../../exports/include/nx-X11/Xtrans/Xtrans.c
(gdb) n
848 in ../../exports/include/nx-X11/Xtrans/Xtrans.c
(gdb) n
840 in ../../exports/include/nx-X11/Xtrans/Xtrans.c
(gdb) n
848 in ../../exports/include/nx-X11/Xtrans/Xtrans.c
(gdb) n
855 in ../../exports/include/nx-X11/Xtrans/Xtrans.c
(gdb) n
864 in ../../exports/include/nx-X11/Xtrans/Xtrans.c
(gdb) print host
$1 = 0x555555bf7d20 "minobo"
(gdb) print port
$2 = 0x555555bf7e00 "0"
(gdb) print ciptr
$3 = (XtransConnInfo) 0x55bf7da0
(gdb) print ciptr->transptr
Cannot access memory at address 0x55bf7da0
```

**Comment by uli42** [comment]
For two reasons:
- I have seen the local/:0 in the backtrace
- I do not have the problem here

**Comment by uli42** [comment]
The question is: Where does that local/:0 come from?

**Comment by uli42** [comment]
Ok, forget that, I see that, too, in my _working_ nxagent

**Comment by sunweaver** [comment]
I checked a bit deeper...

```
458 in ../../exports/include/nx-X11/Xtrans/Xtrans.c
(gdb) n
480 in ../../exports/include/nx-X11/Xtrans/Xtrans.c
(gdb) print ciptr
$7 = (XtransConnInfo) 0x555555bf7da0

[...]

Program received signal SIGSEGV, Segmentation fault.
_X11TransConnect (ciptr=ciptr@entry=0x55bf7da0, address=address@entry=0x7fffffffdc20 "local/:0") at ../../exports/include/nx-X11/Xtrans/Xtrans.c:864
864 in ../../exports/include/nx-X11/Xtrans/Xtrans.c
(gdb) print ciptr
$11 = (XtransConnInfo) 0x55bf7da0
```

It seems that the address of ciptr gets crippled. In _X11TransOpen, I initially get 0x555555bf7da0. In _X11TransConnect what remains is: 0x55bf7da0.

Any clue why that happens?

**Comment by uli42** [comment]
Hmm, might be the compiler, maybe we shoudl concentrate on the warnings

**Comment by uli42** [comment]
My backtrace differs in XOpenDisplay already:

#2  0x00007ffff5c3ef14 in XOpenDisplay (display=0xb531e0 "") at OpenDis.c:221
       dpy = 0xb531e0
        i = 11761344
        j = 1
        k = 32767
        display_name = 0xb382c0 <nxagentDisplayName> ":0"
        endian = 32767
        client = {byteOrder = 0 '\000', pad = 0 '\000', majorVersion =
0, minorVersion = 0, nbytesAuthProto = 0, nbytesAuthString = 0, pad2 =
0}
        idisplay = 0
        prefixread = 0
        conn_auth_name = 0x4000000 <error: Cannot access memory at
address 0x4000000>
        conn_auth_data = 0x7ffff5666cb0 <__restore_rt> "H\307\300\017"
        conn_auth_namelen = 0
        conn_auth_datalen = 0
        setup = 0x0
        fullname = 0x0
        iscreen = 0
        prefix = {success = 0 '\000', lengthReason = 0 '\000',
majorVersion = 0, minorVersion = 0, length = 0}
        vendorlen = 0
        u = {setup = 0x4751f0 <SmartScheduleTimer>, failure = 0x4751f0
<SmartScheduleTimer>
"USH\203\354(\350\205@\371\377\213(H\211\303H\213\005yBg",
          vendor = 0x4751f0 <SmartScheduleTimer>
"USH\203\354(\350\205@\371\377\213(H\211\303H\213\005yBg", sf =
0x4751f0 <SmartScheduleTimer>,
          rp = 0x4751f0 <SmartScheduleTimer>, dp = 0x4751f0
<SmartScheduleTimer>, vp = 0x4751f0 <SmartScheduleTimer>}
        setuplength = 4294967295
        usedbytes = 0
        mask = 140737488345584
        conn_buf_size = 140737488345568
        xlib_buffer_size = 0x40423f "XOpenDisplay"

Compare xlib_buffer_size, usedbytes, prefixread, setuplength,.. Plus:
you do not have vendorlen and u at all! Why?

**Comment by uli42** [comment]
Adding #define NX_TRANS_TEST at the top of OpenDis.c and ConnDis.c
gives me this output:

$ ./nxagent :1

NXAGENT - Version 3.5.99.2

Copyright (c) 2001, 2011 NoMachine (http://www.nomachine.com)
Copyright (c) 2008-2014 Oleksandr Shneyder o.shneyder@phoca-gmbh.de
Copyright (c) 2011-2016 Mike Gabriel mike.gabriel@das-netzwerkteam.de
Copyright (c) 2014-2016 Ulrich Sibiller uli42@gmx.de
Copyright (c) 2014-2016 Mihai Moldovan ionic@ionic.de
Copyright (c) 2015-2016 Qindel Group (http://www.qindel.com)
See https://github.com/ArcticaProject/nx-libs for more information.

Info: Agent running with pid '8197'.
Session: Starting session at 'Thu Oct 13 23:44:26 2016'.

XOpenDisplay: Called with display [:0].
_X11TransConnectDisplay: Called with display_name [:0].
_X11TransConnectDisplay: Entering connection loop.
_X11TransConnectDisplay: Going to call
_X11TransOpenCOTSClient(address) with address [local/:0].
_X11TransConnectDisplay: Going to call _X11TransConnect(trans_conn,address).
_X11TransConnectDisplay: Going to call
_X11TransGetPeerAddr(trans_conn, &family, &saddrlen, &saddr).
_X11TransConnectDisplay: Going to call
_X11TransConvertAddress(&family, &saddrlen, &saddr).
_X11TransConnectDisplay: Out of connection loop.

XOpenDisplay: Connected display with dpy->fd = [5].
Xlib: Running with XLIBBUFFERSIZE [16384] XLIBMINBUFSIZE [8192] buffer
size [16384].
XOpenDisplay: Returning display at [0x19b31d0].
Info: Using alpha channel in render extension.
Info: Not using local device configuration changes.
error opening security policy file /usr/local/lib/nx/X11/xserver/SecurityPolicy
SessionPath not defined
Session: Session started at 'Thu Oct 13 23:44:26 2016'.
Info: Screen [0] resized to geometry [1440x900] fullscreen [0].

What do you see if you try that?

**Comment by sunweaver** [comment]
The build with NX_TRANS_TEST defined gives this:

```
NXAGENT - Version 3.5.99.2

Copyright (c) 2001, 2011 NoMachine (http://www.nomachine.com)
Copyright (c) 2008-2014 Oleksandr Shneyder <o.shneyder@phoca-gmbh.de>
Copyright (c) 2011-2016 Mike Gabriel <mike.gabriel@das-netzwerkteam.de>
Copyright (c) 2014-2016 Ulrich Sibiller <uli42@gmx.de>
Copyright (c) 2014-2016 Mihai Moldovan <ionic@ionic.de>
Copyright (c) 2015-2016 Qindel Group (http://www.qindel.com)
See https://github.com/ArcticaProject/nx-libs for more information.

Info: Agent running with pid '10625'.
Session: Starting session at 'Fri Oct 14 15:45:00 2016'.

XOpenDisplay: Called with display [:0].
_X11TransConnectDisplay: Called with display_name [:0].
_X11TransConnectDisplay: Entering connection loop.
_X11TransConnectDisplay: Going to call _X11TransOpenCOTSClient(address) with address [local/:0].
_X11TransConnectDisplay: Going to call _X11TransConnect(trans_conn,address).
Segmentation fault
```

**Comment by sunweaver** [comment]
FYI: we are one step further. Reason for the segfaults "is" the -pie / -fPIE hardening flags in LDFLAGS / CFLAGS. If PIE hardening is disabled at build time, nxagent does _not_ segfault. With PIE enabled, it segfaults.

**Comment by sunweaver** [comment]
This issue got probably fixed by https://github.com/ArcticaProject/nx-libs/commit/61b8d44f1f76df5abb9e53427f07e9f1ad987e32.

It has been resolved by now, thus closing.
